### ISSUE TITLE
寻路的结果不正确，存在 BUG

### ISSUE THREAD

**Issue by iqverylow** [cloud8352/Jps_BitPrune#2]
应该是什么地方存在bug，寻路出来的结果都不正确呢。

可以试试这个测试地图，比如从 (2,2) 寻路到 (99,99)，计算出来的结果完全不正确。

[map100x101.txt](https://github.com/cloud8352/Jps_BitPrune/files/7746081/map100x101.txt)

**Comment by SisMaker** [comment]
> 应该是什么地方存在bug，寻路出来的结果都不正确呢。
> 
> 可以试试这个测试地图，比如从 (2,2) 寻路到 (99,99)，计算出来的结果完全不正确。
> 
> [map100x101.txt](https://github.com/cloud8352/Jps_BitPrune/files/7746081/map100x101.txt)

你找到问题了没？
